# Generated by Django 6.0.5 on 2026-05-29 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_highlighted',
            field=models.BooleanField(default=False),
        ),
    ]
